### ISSUE TITLE
Failed to pull last commit from github

### ISSUE THREAD

**Issue by kropochev** [pebble/cloudpebble#151]
I am trying to pull last commit from repository https://github.com/kropochev/SpaceTime, but get an error:
>Error: Resource resources/images/menu-icon.png not found in repo.

**Comment by unwiredben** [comment]
This looks to be fixed now.  I was just able to import and build this.  Pull request #168 fixed bw and color file support.

**Comment by kropochev** [comment]
I checked on cloudpebble.net, but the error remained.

**Comment by unwiredben** [comment]
OK, so perhaps the issue is that you can't update a project with those files, but you can create a new one.  Could you try importing into a new project?  That's what I did and I didn't see any issues.

**Comment by kropochev** [comment]
Yes, it works, thanks.

**Comment by dcormier** [comment]
While that does work, it sure would be nice to be able to actually pull from GitHub into an existing project rather than having to delete and recreate it every time I tweak something.

**Comment by davidcorne** [comment]
I'm also having this issue with https://github.com/davidcorne/PebbleColourCalendar.git. I can create a project from it, but I can't then pull from it :(

**Comment by dcormier** [comment]
Additionally, Pebble just had this note in their developer newsletter, making this at least somewhat more important:

>You will now be required to provide a complete asset collection for each platform you target. Existing apps won’t be affected, but you won’t be able to publish a new release until you meet the newer requirements.

**Comment by Katharine** [comment]
That comment is referring to marketing assets on the appstore, and has nothing to do with your app itself.

**Comment by dcormier** [comment]
Oh, OK. Good to know.

**Comment by Omig12** [comment]
Error: Expecting , delimiter: line 39 column 17 (char 1064) 

Getting this error while trying to push to or pull commits from github.

**Comment by Spacerat** [comment]
I've created PR #219 which should fix the problems described by @kropochev and @davidcorne.

Omig12, I can't reproduce your error. Can you give me any more information?

**Comment by Omig12** [comment]
Definitely, I had been trying to pull the latest commit from one of my
repositories <http://github.com/Omig12/ATH-PEBBLE>,  but I was receiving
the error mentioned on the post. Also I tried pushing commits and got the
same error message. But it now seems to be working correctly, many thanks.

On Tue, Sep 29, 2015 at 2:56 PM, Joseph Atkins-Turkish <
notifications@github.com> wrote:

> I've created PR #219 <https://github.com/pebble/cloudpebble/pull/219>
> which should fix the problems described by @kropochev
> <https://github.com/kropochev> and @davidcorne
> <https://github.com/davidcorne>.
>
> Omig12, I can't reproduce your error. Can you give me any more information?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pebble/cloudpebble/issues/151#issuecomment-144156068>.
>



-- 
Israel O. Dilán Pantojas

**Comment by Spacerat** [comment]
OK, in which case, fixed and merged.

**Comment by CocoaBob** [comment]
The problem still exists!

For example, I've an image resource whose file setting is `"file": "example.png"`, and in my assets folder, I put 2 images, they are named `example~bw.png` and `example~color.png`. Then after pulling the repository in CloudPebble, the error comes out: `example.png not found in repo`.

Well, finally I renamed `example~color.png` to `example.png`, and it works.

But actually it wasn't wrong, this naming rule is written in the guide here [Specifying Resources Per Platform](http://developer.getpebble.com/guides/pebble-apps/resources/image-resources/#specifying-resources-per-platform).

Please check it out.

**Comment by Spacerat** [comment]
Ah, although this has been fixed, it hasn't actually been deployed yet! It should be coming within the next few days though - I'll post here when we deploy it.
